seed: 42                  # random seed for reproducible results.

data:
  data_path: "./data/feature_matrix.csv"                 # path to the data
  label_path: "./data/labels.csv"                        # path to the labels
  test_ids:  "./data/test_ids.csv"                       # test id path
  train_ids:  "./data/train_ids.csv"                     # train data path
  label_type: "ANY_30"                                   # Which labels are being used
  save_predictions: "./data/predictions/"
  save_posteriors: "./saved_posteriors"
  figures_path: "./figures"

model:
  frequentist_LASSO: True    # fit frequentist LASSO
  laplace_vi: True        # fit Laplace prior LogReg with Variational Inference
  laplace_mh: True        # fit Laplace prior LogReg with Metrpolis-Hastings
  horseshoe_mh: True      # fit Horseshoe+ prior LogReg with Metropolis-Hastings
  pretrained: True        # If true, than it takes the posterior traces that have already been calculated

uncertainty:
  thresholds: [0.1, 0.3, 0.5]   # List of thresholds to iterate over for coverage experiment
  arbitrary_threshold: 0.16     # arbitrary decision threshold for the plot of sorted predictions and uncertianties

sensitivity_analysis:
  std_factor: 1             # factor that the standard deviation is multiplied with
  use_quantile: False       # Uses credible intervals instead of standard deviation for uncertainty
  quantile: 0.95            # if the credible intervals is used, then this is the quantile
  